### ISSUE TITLE
Worked before, now get errors (haven't add/removed any other plugins)

### ISSUE THREAD

**Issue by FrnsRL** [SamB440/ForcePack#34] opened 2023-08-08 14:47 UTC
[10:43:12] [Server thread/ERROR]: Error occurred while enabling ForcePack v1.2.9 (Is it up to date?)
com.convallyria.forcepack.libs.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: version too high ()
        at com.convallyria.forcepack.libs.commandframework.bukkit.BukkitCommandManager.registerBrigadier(BukkitCommandManager.java:343) ~[?:?]
        at com.convallyria.forcepack.libs.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:125) ~[?:?]
        at com.convallyria.forcepack.spigot.command.Commands.<init>(Commands.java:38) ~[?:?]
        at com.convallyria.forcepack.spigot.ForcePackSpigot.registerCommands(ForcePackSpigot.java:212) ~[?:?]
        at com.convallyria.forcepack.spigot.ForcePackSpigot.onEnable(ForcePackSpigot.java:69) ~[?:?]

[10:43:21] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ForcePack v1.2.9
org.bukkit.event.EventException: null

**Comment by SamB440** [comment] 2023-08-08 14:52
Duplicate of #29.

See comment https://github.com/SamB440/ForcePack/issues/29#issuecomment-1606025763

**Closed by SamB440** 2023-08-08 14:52 UTC

**Comment by FrnsRL** [comment] 2023-08-08 15:09
my apologies
